name: MEAN Full Stack CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ip-172-31-30-129
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dd-backend:latest ./backend

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dd-frontend:latest ./frontend

      - name: Push Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dd-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dd-frontend:latest

      - name: SSH and Deploy on VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            cd /home/ubuntu/crud-dd-task-mean-app
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
            docker system prune -f
